### PR TITLE
Fix build setup

### LINKED ISSUE #17: build errors on windows
I really don't understand what went wrong here?
```julia
julia> Pkg.build("CLFFT")
INFO: Building CLFFT
INFO: Attempting to Create directory C:\Users\Mus\.julia\v0.6\CLFFT\deps\downloads
INFO: Directory C:\Users\Mus\.julia\v0.6\CLFFT\deps\downloads already created
INFO: Downloading file https://github.com/clMathLibraries/clFFT/releases/download/v2.12.2/clFFT-2.12.2-Windows-x64.zip
INFO: Done downloading file https://github.com/clMathLibraries/clFFT/releases/download/v2.12.2/clFFT-2.12.2-Windows-x64.zip
INFO: Attempting to Create directory C:\Users\Mus\.julia\v0.6\CLFFT
INFO: Directory C:\Users\Mus\.julia\v0.6\CLFFT already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\Mus\.julia\v0.6\CLFFT\deps\downloads\clFFT-2.12.2-Windows-x64.zip

Extracting  clFFT-2.12.2-Windows-x64\bin
Extracting  clFFT-2.12.2-Windows-x64\bin\clFFT.dll
Extracting  clFFT-2.12.2-Windows-x64\bin\clFFT-callback-client.exe
Extracting  clFFT-2.12.2-Windows-x64\bin\clFFT-client.exe
Extracting  clFFT-2.12.2-Windows-x64\bin\StatTimer.dll
Extracting  clFFT-2.12.2-Windows-x64\CMake
Extracting  clFFT-2.12.2-Windows-x64\CMake\clFFTConfig.cmake
Extracting  clFFT-2.12.2-Windows-x64\CMake\clFFTConfigVersion.cmake
Extracting  clFFT-2.12.2-Windows-x64\CMake\clFFTTargets.cmake
Extracting  clFFT-2.12.2-Windows-x64\CMake\clFFTTargets-release.cmake
Extracting  clFFT-2.12.2-Windows-x64\include
Extracting  clFFT-2.12.2-Windows-x64\include\clAmdFft.h
Extracting  clFFT-2.12.2-Windows-x64\include\clAmdFft.version.h
Extracting  clFFT-2.12.2-Windows-x64\include\clFFT.h
Extracting  clFFT-2.12.2-Windows-x64\include\clFFT.version.h
Extracting  clFFT-2.12.2-Windows-x64\lib64
Extracting  clFFT-2.12.2-Windows-x64\lib64\import
Extracting  clFFT-2.12.2-Windows-x64\lib64\import\clFFT.lib
Extracting  clFFT-2.12.2-Windows-x64\lib64\import\StatTimer.lib
Extracting  clFFT-2.12.2-Windows-x64\share
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples\fft1d.c
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples\fft1d.exe
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples\fft2d.c
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples\fft2d.exe
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples\fft3d.c
Extracting  clFFT-2.12.2-Windows-x64\share\clFFT\examples\fft3d.exe

Everything is Ok

Folders: 8
Files: 20
Size:       1578625
Compressed: 573181
==================================================================================================================[ ERROR: CLFFT ]==================================================================================================================
LoadError: Path C:\Users\Mus\.julia\v0.6\CLFFT\deps\package was not created successfully (Tried to run `7z x 'C:\Users\Mus\.julia\v0.6\CLFFT\deps\downloads\clFFT-2.12.2-Windows-x64.zip' -y '-oC:\Users\Mus\.julia\v0.6\CLFFT\deps'` )
while loading C:\Users\Mus\.julia\v0.6\CLFFT\deps\build.jl, in expression starting on line 40

====================================================================================================================================================================================================================================================
==================================================================================================================[ BUILD ERRORS ]==================================================================================================================
WARNING: CLFFT had build errors.

 - packages with build errors remain installed in C:\Users\Mus\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("CLFFT")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================================================================================================================================================================
```

### PR DESCRIPTION
**Pull request by musm**
close https://github.com/JuliaGPU/CLFFT.jl/issues/17   otherwise fails on windows to build

https://github.com/JuliaGPU/CLBLAS.jl/blob/master/deps/build.jl will need the same fix

### CODE REVIEW

File: deps/build.jl [hunk 1]
```diff
@@ -1,18 +1,20 @@
...
 libCLFFT = library_dependency("libCLFFT", aliases = libnames)
-archive = "package"
-libpath = "package/bin"
 baseurl = "https://github.com/clMathLibraries/clFFT/releases/download/v2.12.2/clFFT-2.12.2-"
+
 # download a pre-compiled binary (built by GLFW)
 if is_windows()
     if Sys.ARCH == :x86_64
         uri = URI(baseurl * "Windows-x64.zip")
+        basedir = joinpath(@__DIR__, "clFFT-2.12.2-Windows-x64")
```
Comment (vchuravy) [inline deps/build.jl]: `2.12.2` should be a variable outside so that we can update the version in one place.

**Review by vchuravy — APPROVED** [review]

**Comment by musm** [comment]
ok done, not sure how robust that will be but should be sufficient for now  (FYI please squash 😄  )
